FROM mateusoliveira43/poetry:1.4-python3.10-bullseye

# Set the working directory in the container
WORKDIR /app

# Copy your project files (pyproject.toml and poetry.lock) to the container
COPY pyproject.toml poetry.lock /app/

# Disable Poetry's virtual environment creation because the container itself provides an isolated environment
RUN poetry config virtualenvs.create false

# Install dependencies using Poetry
RUN poetry install --no-interaction --no-ansi

# Copy the rest of your application's code to the container
COPY . /app

# Command to run when starting the container
CMD ["uvicorn", "backend_api:app", "--host", "0.0.0.0", "--port", "8000"]