apiVersion: v1
kind: Service
metadata:
  name: app-service  # Clear and simple service name
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: backend-app  # Updated to match deployment labels
