apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: db  # Ensure this matches the labels in your deployment
