version: "3.8"
services:
  db:
    build:
      context: .
      dockerfile: /docker/db/dockerfile
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: /docker/backend/dockerfile
    command: >
      bash -c "
        alembic upgrade head &&
        uvicorn backend_api:app --host 0.0.0.0 --port 8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mysecretpassword@db/bookmap_db

volumes:
  pgdata:
