services:
  graph_db:
    build:
      context: .
      dockerfile: ./docker/graph_db/dockerfile
    ports:
      - "7474:7474" # Port for the browser interface
      - "7687:7687" # DB port
    volumes:
      - graphdata:/data
      - graphdata:/logs
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
    networks:
      - app-network

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./docker/backend/dockerfile
    volumes:
      - .:/app
      - ./profile:/app/profile
    ports:
      - "8000:8000"
    depends_on:
      graph_db:
        condition: service_started
      db:
        condition: service_started
    environment:
      DATABASE_URL: bolt://neo4j:${NEO4J_PASSWORD}@graph_db:7687 # What is this for?
      NEO4J_URI: ${NEO4J_URI}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
    networks:
      - app-network

volumes:
  pgdata:
  graphdata:

networks:
  app-network: # This will create the network if it does not exist
    driver: bridge
    name: bookscraper-network
