version: "3.8"
services:
  db:
    build:
      context: ./docker/db
      dockerfile: dockerfile
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: ./docker/backend
      dockerfile: dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mysecretpassword@db/bookmap_db

volumes:
  pgdata:
