version: "3.8"
services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/dockerfile
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: ./docker/backend/dockerfile
    volumes:
      - .:/app
      - ./profile:/app/profile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mysecretpassword@db/bookmap_db
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network: # This will create the network if it does not exist
    driver: bridge
    name: bookscraper-network
