"""Region should always have a country

Revision ID: 66a8412f492c
Revises: 7a88540c54f4
Create Date: 2025-06-26 21:56:11.233633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a8412f492c'
down_revision: Union[str, None] = '7a88540c54f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regions', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regions', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
