# .github/workflows/ci.yml

name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_USER: myuser
          POSTGRES_DB: bookmap_db
        ports:
          - 5432:5432
        # Set health checks to wait for the database to be ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Build the Docker image
        run: docker-compose build

      - name: Run the Docker container
        run: docker-compose up -d

      - name: Run migrations
        run: docker-compose run app alembic upgrade head

      - name: Run tests
        run: docker-compose run app pytest

      - name: Shut down and remove Docker containers
        run: docker-compose down
